services:
  admin-panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobportal-admin-panel
    ports:
      - "9022:9022"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_APP_NAME=${VITE_APP_NAME}
    restart: unless-stopped
    networks:
      - jobportal-network

networks:
  jobportal-network:
    driver: bridge
